"""Immutable prompt build diagnostics (informational only)."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.ai.features import AIFeature


class PromptDiagnostics(BaseModel):
    """
    Prompt construction diagnostics.

    Builders populate estimated/variable fields.
    Providers later populate ``actual_tokens``.
    No persistence. Never generated by an LLM.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    feature: AIFeature
    template_name: str
    template_path: str | None = None
    prompt_version: str
    builder_version: int
    prompt_hash: str
    estimated_tokens: int = Field(ge=0)
    estimated_prompt_tokens: int = Field(ge=0)
    estimated_completion_tokens: int = Field(ge=0)
    context_size: int = Field(
        ge=0, description="Total characters across variable values"
    )
    actual_tokens: int | None = Field(default=None, ge=0)
    variable_count: int = Field(ge=0)
    missing_variables: tuple[str, ...] = ()
    unused_variables: tuple[str, ...] = ()
    variables_hash: str
    prompt_length: int = Field(ge=0)
