"""Generic AI response envelope — business result separate from provider metadata."""

from __future__ import annotations

from datetime import datetime
from typing import Generic, TypeVar
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.ai.diagnostics import PromptDiagnostics
from app.ai.features import AIFeature
from app.ai.providers.provider_enum import AIProvider
from app.ai.telemetry import GenerationStatus, GenerationTelemetry

T = TypeVar("T")


class ProviderResponseMetadata(BaseModel):
    """
    Provider-owned metadata for a single generation attempt.

    Independent from the business result ``T``. Unknown fields may be ``None``.
    JSON still serializes ``provider`` as a plain string (``\"openai\"``, …).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    generation_id: UUID | None = None
    feature: AIFeature | None = None
    provider: AIProvider
    model: str
    api_version: str | None = None
    finish_reason: str | None = None
    latency_ms: int | None = None
    provider_latency_ms: int | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None
    total_tokens: int | None = None
    cost_usd: float | None = None
    cached: bool = False
    retry_count: int = Field(default=0, ge=0)
    generation_status: GenerationStatus | None = None
    request_id: str | None = None
    response_id: str | None = None
    system_fingerprint: str | None = None
    fallback_used: bool = False
    fallback_reason: str | None = None


class AIQualityMetadata(BaseModel):
    """
    Deterministic quality / provenance metadata for a grounded AI response.

    Populated by ``AIService`` after grounding — never generated by an LLM.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    grounded: bool
    validation_passed: bool
    cache_hit: bool
    provider: AIProvider
    model: str
    prompt_version: str
    builder_version: int
    schema_version: str
    prompt_hash: str | None = None
    feature: AIFeature | None = None


class AIResponse(BaseModel, Generic[T]):
    """
    Typed generation envelope.

    ``result`` is the grounded (or provider-parsed) business payload.
    ``quality`` is deterministic platform metadata (never LLM-authored).
    ``provider_metadata`` holds provider-only facts (model, tokens, latency, …).
    ``generation_id`` correlates response, telemetry, and provider metadata.
    """

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    result: T = Field(description="Structured business generation result")
    generation_id: UUID | None = None
    quality: AIQualityMetadata | None = None
    provider_metadata: ProviderResponseMetadata
    diagnostics: PromptDiagnostics | None = None
    telemetry: GenerationTelemetry | None = None
    session_id: UUID | str | None = None
    generated_at: datetime

    @property
    def metadata(self) -> ProviderResponseMetadata:
        """Backward-compatible alias for ``provider_metadata``."""
        return self.provider_metadata
