"""
Technical finding ID → business impact templates.

Each mapping is deterministic and hedged (ENGINE_SPEC §15) — no fabricated revenue.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.engines.common.findings import Severity
from app.engines.business.schemas import BusinessCategory


@dataclass(frozen=True, slots=True)
class BusinessTemplate:
    """One technical → business translation."""

    business_id: str
    rule_id: str
    category: BusinessCategory
    severity: Severity
    title: str
    why_it_matters: str
    business_consequence: str
    business_area: str
    customer_impact: str


# Exact source finding id → business template.
BUSINESS_MAPPINGS: dict[str, BusinessTemplate] = {
    # --- SEO ---
    "seo.title.missing": BusinessTemplate(
        business_id="biz.seo.missing_title_visibility",
        rule_id="seo.missing_title",
        category=BusinessCategory.SEO_IMPACT,
        severity=Severity.HIGH,
        title="Search visibility impacted by missing title",
        why_it_matters="Search engines and browser tabs rely on the page title as the primary identity signal.",
        business_consequence="Weaker SERP presentation and lower click-through potential from organic search.",
        business_area="Organic acquisition / SEO",
        customer_impact="Shoppers may skip an unlabeled result in favor of clearer competitors.",
    ),
    "seo.title.empty": BusinessTemplate(
        business_id="biz.seo.empty_title_visibility",
        rule_id="seo.empty_title",
        category=BusinessCategory.SEO_IMPACT,
        severity=Severity.HIGH,
        title="Empty title weakens search visibility",
        why_it_matters="An empty title provides no usable snippet label in search results.",
        business_consequence="Reduced organic CTR and brand recognition in SERPs.",
        business_area="Organic acquisition / SEO",
        customer_impact="Users cannot quickly identify what the page offers.",
    ),
    "seo.meta_description.missing": BusinessTemplate(
        business_id="biz.marketing.missing_meta_ctr",
        rule_id="seo.missing_meta_description",
        category=BusinessCategory.MARKETING,
        severity=Severity.HIGH,
        title="Missing meta description reduces CTR potential",
        why_it_matters="Meta descriptions often influence the SERP snippet that users read before clicking.",
        business_consequence="Lower CTR from search even when rankings are adequate.",
        business_area="Organic marketing / SERP messaging",
        customer_impact="Prospects get a less persuasive preview of the offer.",
    ),
    "seo.headings.multiple_h1": BusinessTemplate(
        business_id="biz.seo.multiple_h1_hierarchy",
        rule_id="seo.multiple_h1",
        category=BusinessCategory.SEO_IMPACT,
        severity=Severity.MEDIUM,
        title="Multiple H1s blur content hierarchy",
        why_it_matters="A single clear H1 helps humans and crawlers understand the primary topic.",
        business_consequence="Diluted topical clarity that can weaken content effectiveness.",
        business_area="Content / SEO",
        customer_impact="Readers may struggle to grasp the page's main message quickly.",
    ),
    "seo.headings.missing_h1": BusinessTemplate(
        business_id="biz.seo.missing_h1_hierarchy",
        rule_id="seo.missing_h1",
        category=BusinessCategory.SEO_IMPACT,
        severity=Severity.HIGH,
        title="Missing H1 hurts content hierarchy",
        why_it_matters="Pages without an H1 lack a clear primary heading for structure and scanning.",
        business_consequence="Weaker content comprehension and SEO topical signals.",
        business_area="Content / SEO",
        customer_impact="Visitors may bounce before understanding the page purpose.",
    ),
    "seo.headings.skipped_hierarchy": BusinessTemplate(
        business_id="biz.ux.broken_heading_hierarchy",
        rule_id="seo.skipped_hierarchy",
        category=BusinessCategory.UX,
        severity=Severity.MEDIUM,
        title="Broken heading hierarchy hurts comprehension",
        why_it_matters="Skipped heading levels make content harder to scan and navigate.",
        business_consequence="Higher cognitive load and weaker content engagement.",
        business_area="Content UX",
        customer_impact="Users may miss key sections or abandon the page.",
    ),
    "seo.images.missing_alt": BusinessTemplate(
        business_id="biz.a11y.missing_alt_reach",
        rule_id="seo.missing_alt",
        category=BusinessCategory.ACCESSIBILITY_IMPACT,
        severity=Severity.HIGH,
        title="Missing image alt limits reach and inclusion",
        why_it_matters="Alt text supports assistive tech and can aid image search discovery.",
        business_consequence="Lost inclusive reach and potential image-search visibility.",
        business_area="Accessibility / SEO",
        customer_impact="Screen-reader users and some search surfaces miss image meaning.",
    ),
    "seo.viewport.missing": BusinessTemplate(
        business_id="biz.conversion.missing_viewport_mobile",
        rule_id="seo.missing_viewport",
        category=BusinessCategory.CONVERSION,
        severity=Severity.HIGH,
        title="Missing viewport harms mobile conversion",
        why_it_matters="Without a viewport meta tag, mobile layouts often render poorly.",
        business_consequence="Higher bounce and lower conversion on mobile traffic.",
        business_area="Mobile conversion",
        customer_impact="Mobile visitors face pinch-zoom friction and unusable layouts.",
    ),
    "seo.language.missing": BusinessTemplate(
        business_id="biz.marketing.missing_lang",
        rule_id="seo.missing_lang",
        category=BusinessCategory.MARKETING,
        severity=Severity.MEDIUM,
        title="Missing language signal weakens localization",
        why_it_matters="html lang helps browsers and search engines serve the right audience.",
        business_consequence="Weaker localization and accessibility signals.",
        business_area="International / SEO",
        customer_impact="Assistive tools may mis-pronounce content; wrong locale hints.",
    ),
    # --- Accessibility ---
    "a11y.images.missing_alt": BusinessTemplate(
        business_id="biz.a11y.alt_compliance",
        rule_id="a11y.missing_alt",
        category=BusinessCategory.ACCESSIBILITY_IMPACT,
        severity=Severity.HIGH,
        title="Missing alt creates accessibility and brand risk",
        why_it_matters="Informative images without alternatives exclude assistive-tech users.",
        business_consequence="Compliance exposure and brand perception risk.",
        business_area="Accessibility / Compliance",
        customer_impact="Customers using screen readers cannot understand image content.",
    ),
    "a11y.forms.missing_label": BusinessTemplate(
        business_id="biz.conversion.missing_labels_friction",
        rule_id="a11y.missing_labels",
        category=BusinessCategory.CONVERSION,
        severity=Severity.HIGH,
        title="Missing labels increase form completion friction",
        why_it_matters="Unlabeled fields raise error rates and abandonment in lead/checkout flows.",
        business_consequence="Fewer completed forms and lost leads/revenue opportunities.",
        business_area="Conversion / Lead capture",
        customer_impact="Users guess field purpose or abandon the form.",
    ),
    "a11y.forms.missing_accessible_name": BusinessTemplate(
        business_id="biz.conversion.missing_accessible_name",
        rule_id="a11y.missing_accessible_name",
        category=BusinessCategory.CONVERSION,
        severity=Severity.HIGH,
        title="Unnamed controls block form completion",
        why_it_matters="Controls without accessible names are unusable for many customers.",
        business_consequence="Conversion friction in critical journeys.",
        business_area="Conversion",
        customer_impact="Assistive-tech users cannot complete required fields.",
    ),
    "a11y.buttons.empty": BusinessTemplate(
        business_id="biz.conversion.empty_buttons",
        rule_id="a11y.empty_buttons",
        category=BusinessCategory.CONVERSION,
        severity=Severity.HIGH,
        title="Empty buttons create conversion friction",
        why_it_matters="Buttons without names are unclear CTAs for many users and tools.",
        business_consequence="Missed clicks on primary conversion actions.",
        business_area="Conversion / UX",
        customer_impact="Customers cannot tell what an action does before activating it.",
    ),
    "a11y.headings.multiple_h1": BusinessTemplate(
        business_id="biz.ux.multiple_h1",
        rule_id="a11y.multiple_h1",
        category=BusinessCategory.UX,
        severity=Severity.MEDIUM,
        title="Multiple H1s weaken content scanning",
        why_it_matters="Competing top-level headings confuse page structure.",
        business_consequence="Reduced comprehension and engagement.",
        business_area="Content UX",
        customer_impact="Readers may not identify the primary topic.",
    ),
    "a11y.headings.skipped_levels": BusinessTemplate(
        business_id="biz.ux.skipped_headings",
        rule_id="a11y.skipped_headings",
        category=BusinessCategory.UX,
        severity=Severity.MEDIUM,
        title="Skipped headings hurt comprehension",
        why_it_matters="Irregular heading jumps break reading order and outline navigation.",
        business_consequence="Weaker content usability and accessibility perception.",
        business_area="UX / Content",
        customer_impact="Keyboard and screen-reader users lose structure cues.",
    ),
    "a11y.documents.missing_viewport": BusinessTemplate(
        business_id="biz.conversion.a11y_missing_viewport",
        rule_id="a11y.missing_viewport",
        category=BusinessCategory.CONVERSION,
        severity=Severity.HIGH,
        title="Missing viewport reduces mobile conversions",
        why_it_matters="Mobile rendering without viewport meta often breaks usability.",
        business_consequence="Mobile conversion and engagement decline.",
        business_area="Mobile conversion",
        customer_impact="Mobile customers struggle to use the page.",
    ),
    "a11y.documents.missing_title": BusinessTemplate(
        business_id="biz.brand.missing_document_title",
        rule_id="a11y.missing_title",
        category=BusinessCategory.BRAND,
        severity=Severity.HIGH,
        title="Missing document title weakens brand presence",
        why_it_matters="Titles appear in tabs, history, and assistive tech page lists.",
        business_consequence="Weaker brand recall and navigation context.",
        business_area="Brand / UX",
        customer_impact="Users lose orientation when switching tabs.",
    ),
    "a11y.landmarks.missing_main": BusinessTemplate(
        business_id="biz.a11y.missing_main_landmark",
        rule_id="a11y.missing_main",
        category=BusinessCategory.ACCESSIBILITY_IMPACT,
        severity=Severity.MEDIUM,
        title="Missing main landmark slows task completion",
        why_it_matters="Landmarks help users jump to primary content quickly.",
        business_consequence="Higher effort for assistive-tech customers.",
        business_area="Accessibility / UX",
        customer_impact="Screen-reader users take longer to reach offers or forms.",
    ),
    # --- Security ---
    "sec.headers.missing_csp": BusinessTemplate(
        business_id="biz.trust.missing_csp",
        rule_id="sec.missing_csp",
        category=BusinessCategory.TRUST,
        severity=Severity.MEDIUM,
        title="Missing CSP reduces customer trust posture",
        why_it_matters="Content-Security-Policy limits injection attacks that can deface or steal data.",
        business_consequence="Higher perceived and actual risk of content/script abuse.",
        business_area="Trust / Security posture",
        customer_impact="Customers face greater risk of malicious script interference.",
    ),
    "sec.https.non_https_url": BusinessTemplate(
        business_id="biz.trust.http_page",
        rule_id="sec.non_https",
        category=BusinessCategory.TRUST,
        severity=Severity.CRITICAL,
        title="HTTP page undermines security confidence",
        why_it_matters="Browsers warn on non-HTTPS pages and block secure features.",
        business_consequence="Immediate trust damage and potential abandoned sessions.",
        business_area="Trust / Brand",
        customer_impact="Visitors see 'Not secure' warnings before engaging.",
    ),
    "sec.headers.missing_hsts": BusinessTemplate(
        business_id="biz.trust.missing_hsts",
        rule_id="sec.missing_hsts",
        category=BusinessCategory.TRUST,
        severity=Severity.HIGH,
        title="Missing HSTS weakens transport trust",
        why_it_matters="HSTS keeps returning visitors on HTTPS and resists downgrade attacks.",
        business_consequence="Weaker long-term security posture signal.",
        business_area="Trust / Security",
        customer_impact="Repeat visitors may be more exposed to interception risks.",
    ),
    "sec.forms.sensitive_over_http": BusinessTemplate(
        business_id="biz.revenue.sensitive_http_forms",
        rule_id="sec.sensitive_http_forms",
        category=BusinessCategory.REVENUE,
        severity=Severity.CRITICAL,
        title="Sensitive forms over HTTP threaten revenue trust",
        why_it_matters="Credentials and PII submitted over HTTP can be intercepted.",
        business_consequence="Severe trust and compliance risk around revenue-critical flows.",
        business_area="Revenue / Trust",
        customer_impact="Customers risk exposing passwords or personal data.",
    ),
    "sec.disclosure.server_header": BusinessTemplate(
        business_id="biz.brand.server_disclosure",
        rule_id="sec.server_header",
        category=BusinessCategory.BRAND,
        severity=Severity.INFO,
        title="Server header disclosure is a minor brand/tech leak",
        why_it_matters="Exposing stack details aids attackers fingerprinting the site.",
        business_consequence="Slightly easier reconnaissance against the brand's stack.",
        business_area="Brand / Security hygiene",
        customer_impact="Indirect — increases attacker convenience, not visitor UX.",
    ),
    # --- Performance ---
    "perf.images.missing_lazy_loading": BusinessTemplate(
        business_id="biz.perf.missing_lazy_experience",
        rule_id="perf.missing_lazy",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.MEDIUM,
        title="Missing lazy loading slows page experience",
        why_it_matters="Eager images compete with above-the-fold resources.",
        business_consequence="Slower perceived load and higher bounce risk.",
        business_area="Performance / Experience",
        customer_impact="Visitors wait longer before the page feels ready.",
    ),
    "perf.dom.excessive_nodes": BusinessTemplate(
        business_id="biz.perf.large_dom_cost",
        rule_id="perf.large_dom",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.HIGH,
        title="Large DOM increases rendering cost",
        why_it_matters="Oversized DOMs slow style, layout, and interaction work.",
        business_consequence="Sluggish UX that can suppress engagement and conversion.",
        business_area="Performance / UX",
        customer_impact="Scrolling and interactions feel laggy, especially on mobile.",
    ),
    "perf.js.large_script_count": BusinessTemplate(
        business_id="biz.perf.large_scripts",
        rule_id="perf.large_scripts",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.MEDIUM,
        title="Large script volume taxes customer devices",
        why_it_matters="Many scripts increase download and main-thread work.",
        business_consequence="Slower interactivity and weaker mobile experience.",
        business_area="Performance",
        customer_impact="Pages take longer to become usable after first paint.",
    ),
    "perf.caching.missing_cache_control": BusinessTemplate(
        business_id="biz.perf.missing_cache_control",
        rule_id="perf.missing_cache_control",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.MEDIUM,
        title="Missing Cache-Control hurts repeat-visit speed",
        why_it_matters="Without caching headers, browsers may re-download assets unnecessarily.",
        business_consequence="Worse repeat-visit performance and higher bandwidth cost.",
        business_area="Performance / Retention",
        customer_impact="Returning customers reload content that should feel instant.",
    ),
    "perf.network.too_many_third_party_domains": BusinessTemplate(
        business_id="biz.compliance.third_party_domains",
        rule_id="perf.third_party_domains",
        category=BusinessCategory.COMPLIANCE,
        severity=Severity.HIGH,
        title="Too many third-party domains raise privacy and latency risk",
        why_it_matters="Each third-party origin adds DNS/TLS cost and expands data-sharing surface.",
        business_consequence="Privacy/compliance scrutiny plus slower load times.",
        business_area="Compliance / Performance",
        customer_impact="More trackers/vendors touch the session; pages feel slower.",
    ),
    "perf.css.render_blocking": BusinessTemplate(
        business_id="biz.perf.render_blocking_css",
        rule_id="perf.render_blocking_css",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.HIGH,
        title="Render-blocking CSS delays first meaningful paint",
        why_it_matters="Blocking stylesheets postpone first paint and content visibility.",
        business_consequence="Higher early bounce probability before value is seen.",
        business_area="Performance / Conversion",
        customer_impact="Users stare at a blank or incomplete page longer.",
    ),
    "perf.compression.missing_content_encoding": BusinessTemplate(
        business_id="biz.perf.missing_compression",
        rule_id="perf.missing_compression",
        category=BusinessCategory.PERFORMANCE_IMPACT,
        severity=Severity.MEDIUM,
        title="Missing compression increases transfer time",
        why_it_matters="Uncompressed HTML/CSS/JS transfers more bytes than necessary.",
        business_consequence="Slower loads on constrained networks.",
        business_area="Performance",
        customer_impact="Mobile and low-bandwidth users wait longer.",
    ),
}


def resolve_template(source_finding_id: str) -> BusinessTemplate | None:
    """Return an exact mapping, or ``None`` if unmapped."""
    return BUSINESS_MAPPINGS.get(source_finding_id)
